//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Error Error envelope. Matches the Node.js backend error shape.
type Error struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// StudentId defines model for StudentId.
type StudentId = int64

// BadGateway Error envelope. Matches the Node.js backend error shape.
type BadGateway = Error

// BadRequest Error envelope. Matches the Node.js backend error shape.
type BadRequest = Error

// InternalError Error envelope. Matches the Node.js backend error shape.
type InternalError = Error

// NotFound Error envelope. Matches the Node.js backend error shape.
type NotFound = Error

// Unauthorized Error envelope. Matches the Node.js backend error shape.
type Unauthorized = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStudentReport Generate and download a PDF report for a student.
	// (GET /api/v1/students/{id}/report)
	GetStudentReport(w http.ResponseWriter, r *http.Request, id StudentId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStudentReport operation middleware
func (siw *ServerInterfaceWrapper) GetStudentReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id StudentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStudentReport(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/students/{id}/report", wrapper.GetStudentReport)

	return m
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetStudentReportRequestObject struct {
	Id StudentId `json:"id"`
}

type GetStudentReportResponseObject interface {
	VisitGetStudentReportResponse(w http.ResponseWriter) error
}

type GetStudentReport200ResponseHeaders struct {
	ContentDisposition *string
}

type GetStudentReport200ApplicationpdfResponse struct {
	Body          io.Reader
	Headers       GetStudentReport200ResponseHeaders
	ContentLength int64
}

func (response GetStudentReport200ApplicationpdfResponse) VisitGetStudentReportResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetStudentReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GetStudentReport400JSONResponse) VisitGetStudentReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStudentReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetStudentReport401JSONResponse) VisitGetStudentReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetStudentReport404JSONResponse struct{ NotFoundJSONResponse }

func (response GetStudentReport404JSONResponse) VisitGetStudentReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetStudentReport500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetStudentReport500JSONResponse) VisitGetStudentReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetStudentReport502JSONResponse struct{ BadGatewayJSONResponse }

func (response GetStudentReport502JSONResponse) VisitGetStudentReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetStudentReport Generate and download a PDF report for a student.
	// (GET /api/v1/students/{id}/report)
	GetStudentReport(ctx context.Context, request GetStudentReportRequestObject) (GetStudentReportResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetStudentReport operation middleware
func (sh *strictHandler) GetStudentReport(w http.ResponseWriter, r *http.Request, id StudentId) {
	var request GetStudentReportRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStudentReport(ctx, request.(GetStudentReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStudentReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStudentReportResponseObject); ok {
		if err := validResponse.VisitGetStudentReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFbNcttGDH4VzLYzdVSGlPPTZnRzmybxIakncU6xZwztQuKm5C6zC9pxPZrpQ/QJ+yQd7JL6idQkl+Ym",
	"igTw4QM+AHdK+7bzjhxHNbtTHQZsiSmkpzfcG3J8auTBUNTBdmy9UzP1qm8pWA1WPrALSwH8ArgmiNkI",
	"jvpIIZbW3CtVoawYdci1KpTDltRMWaMKFehDbwMZNePQU6GirqlFibfwoUWW7xz/9EgVqrXOtn2rZseF",
	"4tuO8itaUlCr1Upcxc67SAn6L2ieI9MN3sqT9o7JsfzErmusRkmjeh8ll7utoN8HWqiZ+q7a0FLlt7H6",
	"LQQ/hNrl4rwm6LvIgbCFOeo/yBnQvm8MOM8wJwiEuiYDPkAg7oMjA+iAxGOpVoXAfU0feor8beCGHAxu",
	"MEKLjXBNJiE5dUzBYZPN/3cwJw56Rx870kwmEwJe6z4EMnBT24agC15TjNYtU38N0BPYV56f+d6Zb0oa",
	"mXWPG08x1Zg+2gHSW4c91z7YP+kbwDrpuRYBZq+wQNvkNovCmHdgI1h3jY2V6q5GfSWJrCu86zL9DeSu",
	"qfEdlfASWdcUE/evvKHyfVw3ea5XrLEjEXkXfEeBbZYgHfb/om/R3Q+EBucNDS5aihGXyckg7cjBuqXK",
	"wh5nxLvB6eX6Mz9/T5ozNdYt/H6889pGiB1puxhpyh/MJakbD7EPC9QUZxfuwk1gMhm1PJnAP3/9nYda",
	"P4/E44hL1ZZ+HPl4o2vvG3iJDpfUSmcMDF04AK6RgQVFa3XwkcK11QQT7V3sW4oTOLqqsLPV9XElvVM1",
	"fmndFWA2X78bmi5Wd9asru6V8DaSAfawJEcBmRI23/NcJAEvzs/PQDeWHJc5r0CdD7yV1cnZ6SFg8oPi",
	"RIIfHY5eZVf/CcK6LQzJXRBv6AwgSOXMgAwWPkCa4iGXhilyLKUSv3eU/4uAgSCS7CYR343lOkW5GguV",
	"uIKrARQwLiNEn4nX3tCFG9BJBI0OGMOSGGQqj+UH6wx15CTJ5ra8cKpQjdXkIklPDTvr5em5iJwtN/I4",
	"LEg4e/oMXqfo8GZg8ccDTfF2XBInZ6eqUNcUYu7R43JaTsWx78hhZ9VMPSyn5UPRFHKd5LTfImp2tyrU",
	"wQJ95tVQO3G5JN7XyzPa6H0w/CGCQUZYBN+m/9fb7tOBIHUIQmKIFw7B+BvX+EHpQlKOXYKM07HfHF1T",
	"APb9OqwEm2MkMDaQXpfDjx0hB4l6TjzQn5lPXG2ul3eHJ+rmk2pz3awuP7keHkynn5ndnVnsju71qTK3",
	"DsPtgSF2cJ+MkjHb1KhC1YRmuMB+zQjuP7Wx89Fm408rdsKMuk4dtpCFKb2ahJXX5eh2g3cP3apQj3LK",
	"hzhbU1NtnSnJ5PjLJjv7MBk9+rLReq+vCvX4a4DtXi3J6sFXpTMeiWk39m0r5ZPeGoaZ9PPYxIBbdUr8",
	"4iiQtLdwKW2nBnldJlbz7MvtuFu0YVzsTN6jNIyHp3uqUH1o1EzVzN2sqhqvsal95NmT6ROZFns3+Ze2",
	"ERyNwv2M88fT6c9JEUNCe/eBM523jiPIuD5wFGz23ZjXuOnKzfE/AjmQxiZAYs/A/HZ/S225GghfXa7+",
	"DQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
