// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gaarutyunov/skill-test/go-service/internal/port (interfaces: StudentRepository,ReportGenerator)
//
// Generated by this command:
//
//	mockgen -destination internal/port/mock/mock_port.go -package mock github.com/gaarutyunov/skill-test/go-service/internal/port StudentRepository,ReportGenerator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/gaarutyunov/skill-test/go-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentRepository is a mock of StudentRepository interface.
type MockStudentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudentRepositoryMockRecorder
	isgomock struct{}
}

// MockStudentRepositoryMockRecorder is the mock recorder for MockStudentRepository.
type MockStudentRepositoryMockRecorder struct {
	mock *MockStudentRepository
}

// NewMockStudentRepository creates a new mock instance.
func NewMockStudentRepository(ctrl *gomock.Controller) *MockStudentRepository {
	mock := &MockStudentRepository{ctrl: ctrl}
	mock.recorder = &MockStudentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentRepository) EXPECT() *MockStudentRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockStudentRepository) FindByID(ctx context.Context, id int64) (*domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStudentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStudentRepository)(nil).FindByID), ctx, id)
}

// MockReportGenerator is a mock of ReportGenerator interface.
type MockReportGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockReportGeneratorMockRecorder
	isgomock struct{}
}

// MockReportGeneratorMockRecorder is the mock recorder for MockReportGenerator.
type MockReportGeneratorMockRecorder struct {
	mock *MockReportGenerator
}

// NewMockReportGenerator creates a new mock instance.
func NewMockReportGenerator(ctrl *gomock.Controller) *MockReportGenerator {
	mock := &MockReportGenerator{ctrl: ctrl}
	mock.recorder = &MockReportGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportGenerator) EXPECT() *MockReportGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockReportGenerator) Generate(ctx context.Context, student *domain.Student) (*domain.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, student)
	ret0, _ := ret[0].(*domain.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockReportGeneratorMockRecorder) Generate(ctx, student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockReportGenerator)(nil).Generate), ctx, student)
}
