// Code generated by OpenTelemetry Weaver. DO NOT EDIT.
// Regenerate with `make semconv` (source: semconv/registry).

// Package semconv holds the project's OpenTelemetry semantic conventions.
//
// These attribute keys are the canonical constants the service MUST use when
// annotating spans and metrics.
package semconv

import "go.opentelemetry.io/otel/attribute"

// Attribute keys.
const (
	// AdapterNameKey: Configured adapter implementation name.
	AdapterNameKey = attribute.Key("adapter.name")
	// AdapterPortKey: Hexagonal port name the adapter is bound to.
	AdapterPortKey = attribute.Key("adapter.port")
	// BuildDateKey: RFC3339 timestamp at which the binary was built.
	BuildDateKey = attribute.Key("build.date")
	// ReportFileNameKey: Suggested download file name of the report.
	ReportFileNameKey = attribute.Key("report.file_name")
	// ReportFormatKey: Output format of the generated report.
	ReportFormatKey = attribute.Key("report.format")
	// ReportPageCountKey: Number of pages in the generated PDF document.
	ReportPageCountKey = attribute.Key("report.page_count")
	// ReportSizeBytesKey: Size in bytes of the generated report payload.
	ReportSizeBytesKey = attribute.Key("report.size_bytes")
	// StudentIdKey: Unique identifier of the student (users.id in the backend).
	StudentIdKey = attribute.Key("student.id")
	// UpstreamOperationKey: Logical upstream operation invoked.
	UpstreamOperationKey = attribute.Key("upstream.operation")
)

// AdapterName returns an attribute.KeyValue for the "adapter.name" attribute.
func AdapterName(v string) attribute.KeyValue { return AdapterNameKey.String(v) }

// AdapterPort returns an attribute.KeyValue for the "adapter.port" attribute.
func AdapterPort(v string) attribute.KeyValue { return AdapterPortKey.String(v) }

// BuildDate returns an attribute.KeyValue for the "build.date" attribute.
func BuildDate(v string) attribute.KeyValue { return BuildDateKey.String(v) }

// ReportFileName returns an attribute.KeyValue for the "report.file_name" attribute.
func ReportFileName(v string) attribute.KeyValue { return ReportFileNameKey.String(v) }

// ReportFormat returns an attribute.KeyValue for the "report.format" attribute.
func ReportFormat(v string) attribute.KeyValue { return ReportFormatKey.String(v) }

// ReportPageCount returns an attribute.KeyValue for the "report.page_count" attribute.
func ReportPageCount(v int64) attribute.KeyValue { return ReportPageCountKey.Int64(v) }

// ReportSizeBytes returns an attribute.KeyValue for the "report.size_bytes" attribute.
func ReportSizeBytes(v int64) attribute.KeyValue { return ReportSizeBytesKey.Int64(v) }

// StudentId returns an attribute.KeyValue for the "student.id" attribute.
func StudentId(v int64) attribute.KeyValue { return StudentIdKey.Int64(v) }

// UpstreamOperation returns an attribute.KeyValue for the "upstream.operation" attribute.
func UpstreamOperation(v string) attribute.KeyValue { return UpstreamOperationKey.String(v) }
