// Package report provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package report

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Error Error envelope. Matches the Node.js backend error shape.
type Error struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// StudentId defines model for StudentId.
type StudentId = int64

// BadGateway Error envelope. Matches the Node.js backend error shape.
type BadGateway = Error

// BadRequest Error envelope. Matches the Node.js backend error shape.
type BadRequest = Error

// InternalError Error envelope. Matches the Node.js backend error shape.
type InternalError = Error

// NotFound Error envelope. Matches the Node.js backend error shape.
type NotFound = Error

// Unauthorized Error envelope. Matches the Node.js backend error shape.
type Unauthorized = Error

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetStudentReport Generate and download a PDF report for a student.
	//
	// Fetches the student's data from the upstream Node.js backend and renders
	// a downloadable PDF report. The service never touches the database directly.
	//
	// Corresponds with GET /api/v1/students/{id}/report (the `GetStudentReport` operationId).
	GetStudentReport(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetStudentReport Generate and download a PDF report for a student.
//
// Fetches the student's data from the upstream Node.js backend and renders
// a downloadable PDF report. The service never touches the database directly.
//
// Corresponds with GET /api/v1/students/{id}/report (the `GetStudentReport` operationId).
func (c *Client) GetStudentReport(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStudentReportRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetStudentReportRequest constructs an http.Request for the GetStudentReport method
func NewGetStudentReportRequest(server string, id StudentId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/students/%s/report", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetStudentReportWithResponse Generate and download a PDF report for a student.
	//
	// Fetches the student's data from the upstream Node.js backend and renders
	// a downloadable PDF report. The service never touches the database directly.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/students/{id}/report (the `GetStudentReport` operationId).
	GetStudentReportWithResponse(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*GetStudentReportResponse, error)
}

// GetStudentReportResponse200Headers the declared response headers of an HTTP 200 response for GetStudentReport
type GetStudentReportResponse200Headers struct {
	ContentDisposition *string
}

type GetStudentReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalError
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *BadGateway
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetStudentReportResponse200Headers
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetStudentReportResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetStudentReportResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetStudentReportResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetStudentReportResponse) GetJSON500() *InternalError {
	return r.JSON500
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r GetStudentReportResponse) GetJSON502() *BadGateway {
	return r.JSON502
}

// GetBody returns the raw response body bytes
func (r GetStudentReportResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetStudentReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStudentReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetStudentReportResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetStudentReportWithResponse Generate and download a PDF report for a student.
//
// Fetches the student's data from the upstream Node.js backend and renders
// a downloadable PDF report. The service never touches the database directly.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/students/{id}/report (the `GetStudentReport` operationId).
func (c *ClientWithResponses) GetStudentReportWithResponse(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*GetStudentReportResponse, error) {
	rsp, err := c.GetStudentReport(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStudentReportResponse(rsp)
}

// ParseGetStudentReportResponse parses an HTTP response from a GetStudentReportWithResponse call
func ParseGetStudentReportResponse(rsp *http.Response) (*GetStudentReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStudentReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetStudentReportResponse200Headers
		if values := rsp.Header.Values("Content-Disposition"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Content-Disposition", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ContentDisposition = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}
