// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/goforj/wire"
)

// Injectors from wire.go:

// InitializeApp builds a fully wired App from a config path. The returned
// cleanup function shuts the tracer provider down.
func InitializeApp(ctx context.Context, configPath string) (*App, func(), error) {
	koanf, err := ProvideKoanf(configPath)
	if err != nil {
		return nil, nil, err
	}
	config, err := ProvideConfig(koanf)
	if err != nil {
		return nil, nil, err
	}
	telemetry, cleanup, err := ProvideTelemetry(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider := ProvideTracerProvider(telemetry)
	meterProvider := ProvideMeterProvider(telemetry)
	logger := ProvideLogger()
	client := ProvidePDFClient(tracerProvider)
	dependencies := ProvideDependencies(tracerProvider, meterProvider, logger, client)
	registry := ProvideRegistry(dependencies)
	studentRepository, err := ProvideStudentRepository(registry, config, koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	reportGenerator, err := ProvideReportGenerator(registry, config, koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	generateReport := ProvideGenerateReport(studentRepository, reportGenerator, tracerProvider)
	metricsHandler := ProvideMetricsHandler(telemetry)
	v := ProvideReadinessCheckers(studentRepository)
	handler := NewHTTPHandler(generateReport, tracerProvider, meterProvider, metricsHandler, v)
	server := NewHTTPServer(config, handler)
	v2 := ProvideStarters(studentRepository)
	app := ProvideApp(server, config, v2)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// providerSet is the full dependency graph of the application.
var providerSet = wire.NewSet(
	ProvideKoanf,
	ProvideConfig,
	ProvideLogger,
	ProvideTelemetry,
	ProvideTracerProvider,
	ProvideMeterProvider,
	ProvideMetricsHandler,
	ProvidePDFClient,
	ProvideDependencies,
	ProvideRegistry,
	ProvideStudentRepository,
	ProvideReportGenerator,
	ProvideGenerateReport,
	ProvideStarters,
	ProvideReadinessCheckers,
	NewHTTPHandler,
	NewHTTPServer,
	ProvideApp,
)
