// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/goforj/wire"
)

// Injectors from wire.go:

// InitializeApp builds a fully wired App from a config path. The returned
// cleanup function shuts the tracer provider down.
func InitializeApp(ctx context.Context, configPath string) (*App, func(), error) {
	koanf, err := ProvideKoanf(configPath)
	if err != nil {
		return nil, nil, err
	}
	config, err := ProvideConfig(koanf)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider, cleanup, err := ProvideTracerProvider(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	client := ProvidePDFClient(tracerProvider)
	dependencies := ProvideDependencies(tracerProvider, client)
	registry := ProvideRegistry(dependencies)
	studentRepository, err := ProvideStudentRepository(registry, config, koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	reportGenerator, err := ProvideReportGenerator(registry, config, koanf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	generateReport := ProvideGenerateReport(studentRepository, reportGenerator, tracerProvider)
	handler := NewHTTPHandler(generateReport, tracerProvider)
	server := NewHTTPServer(config, handler)
	app := ProvideApp(server, config)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// providerSet is the full dependency graph of the application.
var providerSet = wire.NewSet(
	ProvideKoanf,
	ProvideConfig,
	ProvideTracerProvider,
	ProvidePDFClient,
	ProvideDependencies,
	ProvideRegistry,
	ProvideStudentRepository,
	ProvideReportGenerator,
	ProvideGenerateReport,
	NewHTTPHandler,
	NewHTTPServer,
	ProvideApp,
)
