// Package upstream provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upstream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// AccountBasic defines model for AccountBasic.
type AccountBasic struct {
	Email *string `json:"email,omitempty"`
	Id    *int64  `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Role  *string `json:"role,omitempty"`
}

// Error Error envelope. Matches the Node.js backend error shape.
type Error struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`

	// Username The user's email address.
	Username string `json:"username"`
}

// StudentDetail Full student profile as returned by the Node.js backend.
type StudentDetail struct {
	AdmissionDate      *string `json:"admissionDate,omitempty"`
	Class              *string `json:"class,omitempty"`
	CurrentAddress     *string `json:"currentAddress,omitempty"`
	Dob                *string `json:"dob,omitempty"`
	Email              string  `json:"email"`
	FatherName         *string `json:"fatherName,omitempty"`
	FatherPhone        *string `json:"fatherPhone,omitempty"`
	Gender             *string `json:"gender,omitempty"`
	GuardianName       *string `json:"guardianName,omitempty"`
	GuardianPhone      *string `json:"guardianPhone,omitempty"`
	Id                 int64   `json:"id"`
	MotherName         *string `json:"motherName,omitempty"`
	MotherPhone        *string `json:"motherPhone,omitempty"`
	Name               string  `json:"name"`
	PermanentAddress   *string `json:"permanentAddress,omitempty"`
	Phone              *string `json:"phone,omitempty"`
	RelationOfGuardian *string `json:"relationOfGuardian,omitempty"`
	ReporterName       *string `json:"reporterName,omitempty"`
	Roll               *int64  `json:"roll,omitempty"`
	Section            *string `json:"section,omitempty"`
	SystemAccess       *bool   `json:"systemAccess,omitempty"`
}

// StudentId defines model for StudentId.
type StudentId = int64

// BadRequest Error envelope. Matches the Node.js backend error shape.
type BadRequest = Error

// Forbidden Error envelope. Matches the Node.js backend error shape.
type Forbidden = Error

// InternalError Error envelope. Matches the Node.js backend error shape.
type InternalError = Error

// NotFound Error envelope. Matches the Node.js backend error shape.
type NotFound = Error

// Unauthorized Error envelope. Matches the Node.js backend error shape.
type Unauthorized = Error

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// LoginWithBody Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
	LoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Login Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
	Login(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStudentDetail Fetch the full detail of a single student.
	//
	// Requires an authenticated session obtained from `login`: the `accessToken`
	// session cookie together with the matching `X-CSRF-Token` header.
	//
	// Corresponds with GET /api/v1/students/{id} (the `GetStudentDetail` operationId).
	GetStudentDetail(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// LoginWithBody Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
func (c *Client) LoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Login Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
func (c *Client) Login(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetStudentDetail Fetch the full detail of a single student.
//
// Requires an authenticated session obtained from `login`: the `accessToken`
// session cookie together with the matching `X-CSRF-Token` header.
//
// Corresponds with GET /api/v1/students/{id} (the `GetStudentDetail` operationId).
func (c *Client) GetStudentDetail(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStudentDetailRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewLoginRequest calls the generic Login builder with application/json body
func NewLoginRequest(server string, body LoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginRequestWithBody constructs an http.Request for the Login method, with any body, and a specified content type
func NewLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetStudentDetailRequest constructs an http.Request for the GetStudentDetail method
func NewGetStudentDetailRequest(server string, id StudentId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/students/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// LoginWithBodyWithResponse Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
	LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginResponse, error)

	// LoginWithResponse Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
	LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginResponse, error)

	// GetStudentDetailWithResponse Fetch the full detail of a single student.
	//
	// Requires an authenticated session obtained from `login`: the `accessToken`
	// session cookie together with the matching `X-CSRF-Token` header.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/students/{id} (the `GetStudentDetail` operationId).
	GetStudentDetailWithResponse(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*GetStudentDetailResponse, error)
}

// LoginResponse200Headers the declared response headers of an HTTP 200 response for Login
type LoginResponse200Headers struct {
	SetCookie *string
}

type LoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AccountBasic
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *LoginResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LoginResponse) GetJSON200() *AccountBasic {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r LoginResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r LoginResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetBody returns the raw response body bytes
func (r LoginResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LoginResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetStudentDetailResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *StudentDetail
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetStudentDetailResponse) GetJSON200() *StudentDetail {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetStudentDetailResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetStudentDetailResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetStudentDetailResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetStudentDetailResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetStudentDetailResponse) GetJSON500() *InternalError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetStudentDetailResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetStudentDetailResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStudentDetailResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetStudentDetailResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// LoginWithBodyWithResponse Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
func (c *ClientWithResponses) LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginResponse, error) {
	rsp, err := c.LoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginResponse(rsp)
}

// LoginWithResponse Authenticate and receive session cookies (accessToken, refreshToken, csrfToken).
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/auth/login (the `Login` operationId).
func (c *ClientWithResponses) LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginResponse, error) {
	rsp, err := c.Login(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginResponse(rsp)
}

// GetStudentDetailWithResponse Fetch the full detail of a single student.
//
// Requires an authenticated session obtained from `login`: the `accessToken`
// session cookie together with the matching `X-CSRF-Token` header.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/students/{id} (the `GetStudentDetail` operationId).
func (c *ClientWithResponses) GetStudentDetailWithResponse(ctx context.Context, id StudentId, reqEditors ...RequestEditorFn) (*GetStudentDetailResponse, error) {
	rsp, err := c.GetStudentDetail(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStudentDetailResponse(rsp)
}

// ParseLoginResponse parses an HTTP response from a LoginWithResponse call
func ParseLoginResponse(rsp *http.Response) (*LoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccountBasic
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers LoginResponse200Headers
		if values := rsp.Header.Values("Set-Cookie"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Set-Cookie", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.SetCookie = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseGetStudentDetailResponse parses an HTTP response from a GetStudentDetailWithResponse call
func ParseGetStudentDetailResponse(rsp *http.Response) (*GetStudentDetailResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStudentDetailResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StudentDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
